### ISSUE TITLE
No way back from the display setup page?

### ISSUE THREAD

**Issue by viper-666** [peepshow-21/ns-flash#14]
Hello,
first thanks for your great work, I have to find out a lot because I want to use it with ioBroker instead of OH.
I don't know if my problem exist because I have bought the US Version but I can't find a way to leave the display setup page.
See picture.
![IMG_20220206_141056](https://user-images.githubusercontent.com/13709294/152682842-14679581-a15d-4513-a59c-751dd0861fd4.jpg)

**Comment by peepshow-21** [comment]
On the latest version I'm sure you can swipe away from that back to home
screen.

On some just before the latest I missed the swipe from that screen.

**Comment by peepshow-21** [comment]
USA version seems to have larger screen too, because the buttons on the
right are off screen on EU version. Will it be usable on USA one because
the screen orientation?

**Comment by viper-666** [comment]
I have installed the tft file from your beta-release.
As you see the screen orientation is fine, the two buttons are on the right hand. The indicators on the screen (if a hardware button is pressed and the relay has activated) are on the wrong side, for the US version they had to be on the right where you see the small buttons? (I think that are indicators who you placed there for debugging).

**Comment by peepshow-21** [comment]
Hi, could be a little tricky

The screens have been designed around having the gui buttons at bottom.
Would mean a different version specifically for that unit (which I don't
even have) would need size the screen differently and the hidden buttons
done differently. They actually sit under the bezel on the EU version.

I also thought the US one still had bottons at the bottom., but it was
mounted vertically, hense the orientation being wrong, as per attached
image.

Is this not the case?

**Comment by viper-666** [comment]
Sorry, I can't help you how the US Version has to be mounted. I'm from Germany and bought the US Version because it has (in the datasheet) a bigger screen.
Both versions have the same screen, the only difference is that at the EU version a part of the screen isn't visible.

**Comment by peepshow-21** [comment]
I'll close this as back works in current version

**Comment by ilexpl01** [comment]
The newest TFT & nxpanel.be files + EU version of NSPanel and swipe back does not work 4 me :/

**Comment by peepshow-21** [comment]
That is exactly my setup. What version does it say when you boot?
If already running do `restart 1` in tasmota.
which screen are you in? and what are you swiping. be careful not to swipe over a button or control as they might get the touch before the swipe and do it's thing. best swipe on button free part of screen.

**Comment by ilexpl01** [comment]
restart 1 performed many times

00:00:00.003 HDW: ESP32-D0WD-V3 
00:00:00.188 UFS: FlashFS mounted with 248 kB free
00:00:00.315 CFG: Loaded from File, Count 165
00:00:00.331 QPC: Count 1
00:00:00.435 BRY: Berry initialized, RAM used=3474 bytes
00:00:00.471 Project tasmota - NSPanel Version 10.1.0.8(fullrules)-2_0_2_2(2022-02-06T17:32:26)
00:00:01.884 NSP: Initializing Driver
00:00:01.904 RSL: RESULT = {"Rule3":{"State":"ON","Once":"OFF","StopOnError":"OFF","Length":0,"Free":511,"Rules":""}}
00:00:01.932 RSL: RESULT = {"Time":"1970-01-01T00:00:01","Uptime":"0T00:00:00","UptimeSec":0,"Heap":192,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":0,"MqttCount":0,"Berry":{"HeapUsed":13,"Objects":250},"POWER1":"OFF","POWER2":"OFF"}
00:00:01.963 BRY: Successfully loaded 'autoexec.be'
00:00:02.009 RSL: RESULT = {"nextion":"bytes('1A')"}
00:00:03.508 WIF: Connecting to AP1 SmartHome Channel 1 BSSId 5A:D4:F7:34:66:0E in mode 11n as tasmota01-4056...
00:00:05.596 WIF: Connected
00:00:05.857 HTP: Web server active on tasmota01-4056 with IP address 192.168.100.201
17:24:36.705 MQT: Attempting connection...
17:24:36.740 MQT: Connected
17:24:36.747 MQT: tele/tasmota01/LWT = Online (retained)
17:24:36.761 MQT: cmnd/tasmota01/POWER = 
17:24:36.776 MQT: tele/tasmota01/INFO1 = {"Info1":{"Module":"NSPanel","Version":"10.1.0.8(fullrules)","FallbackTopic":"cmnd/Tasmota01_fb/","GroupTopic":"cmnd/tasmotas/"}}
17:24:36.816 MQT: tele/tasmota01/INFO2 = {"Info2":{"WebServerMode":"Admin","Hostname":"tasmota01-4056","IPAddress":"192.168.100.201"}}
17:24:36.849 MQT: tele/tasmota01/INFO3 = {"Info3":{"RestartReason":"Software reset CPU","BootCount":27}}
17:24:37.000 MQT: stat/tasmota01/RESULT = {"POWER1":"OFF"}
17:24:37.011 MQT: stat/tasmota01/POWER1 = OFF
17:24:37.024 MQT: stat/tasmota01/RESULT = {"POWER2":"OFF"}
17:24:37.033 MQT: stat/tasmota01/POWER2 = OFF
17:24:37.257 MQT: tele/tasmota01/RESULT = {"init": {"nx-panel": "v1.0.0-beta1", "berry": "", }}UU{"page": {"format": 1, "id": 0, "type": "sync"}}
17:24:38.055 MQT: domoticz/in = {"idx":353,"nvalue":0,"svalue":"","Battery":100,"RSSI":7}
17:24:38.065 MQT: domoticz/in = {"idx":354,"nvalue":0,"svalue":"","Battery":100,"RSSI":7}
17:24:39.055 QPC: Reset
17:24:41.063 MQT: tele/tasmota01/STATE = {"Time":"2022-02-07T17:24:41","Uptime":"0T00:00:10","UptimeSec":10,"Heap":144,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":32,"MqttCount":1,"Berry":{"HeapUsed":12,"Objects":221},"POWER1":"OFF","POWER2":"OFF","Wifi":{"AP":1,"SSId":"SmartHome","BSSId":"5A:D4:F7:34:66:0E","Channel":1,"Mode":"11n","RSSI":72,"Signal":-64,"LinkCount":1,"Downtime":"0T00:00:04"}}
17:24:41.126 MQT: domoticz/in = {"idx":352,"nvalue":0,"svalue":"29.4","Battery":100,"RSSI":7}
17:24:41.141 MQT: tele/tasmota01/SENSOR = {"Time":"2022-02-07T17:24:41","ANALOG":{"Temperature1":29.4},"ESP32":{"Temperature":44.4},"TempUnit":"C"}

I can not swipe out of setup screen.

**Comment by peepshow-21** [comment]
that's an old version. v1.0.0-beta1, should be beta4.
https://github.com/peepshow-21/ns-flash/tree/master/tft

the link at the bottom on the main post;
https://community.openhab.org/t/nxpanel-replacement-firmware-for-sonoff-nspanel/132869?u=m-home
I keep up to date.

**Comment by ilexpl01** [comment]
I would suggest to place this link in https://github.com/peepshow-21/ns-flash/blob/master/README.md

**Comment by ilexpl01** [comment]
thx 4 a hint, swipe back does work !

**Comment by peepshow-21** [comment]
Just for you;
https://github.com/peepshow-21/ns-flash/releases/download/v1.0.0-beta2/ns-flash.jar
![image](https://user-images.githubusercontent.com/42150988/152836401-5b4164d6-bb0b-4438-8d5e-a7b81266b0c4.png)

**Comment by peepshow-21** [comment]
good point. changed.
