### ISSUE TITLE
Negativ temperatures were shown positiv

### ISSUE THREAD

**Issue by viper-666** [peepshow-21/ns-flash#15]
On the weather Icon the temperature is always shown positiv, if you send:
{"weather":{"temp":-8,"icon":"11d","feels":-7}}
both temperatures will shown a positiv value,

**Comment by peepshow-21** [comment]
You are correct. It doesn't render correctly below 0. It will be fixed when I add functionality to be able to set ranges on the gauges. which I plan to too. It get cold here too! :)
Update: actually was a bigger issue, in how I handle the json!! :/ 
not putting quotes around numbers is really a shortcut, if the number could be negative please place in quotes "-7", it will work then
