### ISSUE TITLE
Tutorial Windows IIS Webserver

### ISSUE THREAD

**Issue by viper-666** [peepshow-21/ns-flash#18]
Hello,
because I haven't OH I have to set up a webserver for the TFT file upload.
I thought under Windows the IIS Webserver (what is integrated in Windows since Version 7) is a good choose.
But there where a few things I have to change that your ns-flash.jar has the permissions to write in the webserver folder and that the NS-Panel has access to the files on the webserver.
If you are interested I will write a How To for your Wiki, so that other user have it easy to do that.

**Comment by peepshow-21** [comment]
Good idea. I you want to create something for your specific home automation
backend system, I put a link in to direct people to that page in the main
instructions

**Comment by viper-666** [comment]
Yes, I could also write some instructions how to build up the mqtt messages in ioBroker.
But I have currently only the weather and the temperature and humility on the first page ready.
Have you some instructions how the mqtt messages have to be to create new sides and how to "speak" to the buttons ect. 
I also have problems to find the mqtt messages for the alarm and message field on the first side.

**Comment by peepshow-21** [comment]
I've not written it up yet, but this should get you started.

As you move to a button screen the panel will send this;
```
{"page": {"format": 9, "id": 12, "type": "refresh"}}
```
where id is the room id; study=12, lounge=14,, kind of thing
and format is the style of page
You'll see the number id for pages and icons in the script in this post [look at grooy script](https://community.openhab.org/t/nxpanel-replacement-firmware-for-sonoff-nspanel/132869/2?u=m-home). The script is documented, so it will help you figure that the json mqtt will look like.
Here is an example of what the panel would get back;
```
'{"refresh":{"pid":10,"name":"Lounge","format":6,buttons:[{"bid":1,"label":"Movie","type":1,"state":1,"icon":1},{"bid":2,"label":"Cabin","type":1,"state":0,"icon":1},{"bid":3,"label":"Hall","type":2,"icon":6},{"bid":4,"label":"Bedroom","type":10,"next":11,"state":5,"icon":5},{"bid":5,"label":"Temp","type":10,"next":12,"state":9,"icon":9},{"bid":6,"label":"Light","type":1,"icon":3}]}}'
```

This post here will [explain how to update buttons](https://community.openhab.org/t/nxpanel-replacement-firmware-for-sonoff-nspanel/132869/43?u=m-home). 

The first page id you need make will be id 10. This is the id of the page the panel will request when you swipe from the home. Current it's 8 button page for id 10, but you'll be able to configure it differently shortly.

**Comment by viper-666** [comment]
My tutorial is ready, I have create a pull request. But it seems that my new Wiki page isn't into the pull request, only the needed pictures. If it isn't please tell me, than I will upload a file so you can copy the markdown text from it for the Wiki page.

**Comment by peepshow-21** [comment]
yes, send me the markdown. You need to make sure the pics work from where
they have been merged I guess.

**Comment by viper-666** [comment]
I have send you the file with the answer of your mail from github, I hope you get the attachment. If not I will send it over a other pull request.

**Comment by viper-666** [comment]
Ok, here is the link: https://github.com/viper-666/ns-flash/wiki/HowTo-set-up-a-IIS-Webserver-under-Windows

**Comment by peepshow-21** [comment]
thanks, updated to point to that
