### ISSUE TITLE
Change the weather icons (Future request)

### ISSUE THREAD

**Issue by viper-666** [peepshow-21/ns-flash#19]
It would be cool if you can change the weather icons for some better looking types.
Especial the sun icon looks like a red dot not what I and maybe other expected.
Have a look at this icons: [https://developer.accuweather.com/weather-icons](url)

**Comment by peepshow-21** [comment]
Current ones are taken from here and the icon code is passed directly in
https://openweathermap.org/weather-conditions
so it makes it very easy to make from the openweather binding in OH :)

There is probably scope look at this when all the core stuff is working
well.

**Comment by viper-666** [comment]
Ok, I understood, but the naming for example "01d" is not easy to set under other systems. 
As you mentions you have to map the icons to the weather service you choose. I have to make some tricks to get the output. 
01 will be 1 after mapping, so you have to put a "0" bevor all numbers unter 10 and a "d" after all numbers.
And the icon you choose can be free defined in Nexion Editor or not?

**Comment by peepshow-21** [comment]
you can't pass any graphics into the nextion, which is part of the issue,
everything you need to use needs to be compiled in
