### ISSUE TITLE
ns-flash.jar process result window  (Future request)

### ISSUE THREAD

**Issue by ilexpl01** [peepshow-21/ns-flash#20]
It would be perfect to be informed by ns-flash.jar about completion of the task with the massage.  Please think it over :)

**Comment by viper-666** [comment]
That's right, you have to look hard to see that the ns-flash is ready.

**Comment by peepshow-21** [comment]
I guess I know what I'm looking at. The button stays down, until it's
compete. I just wait until it pops up then start the load. :)

**Comment by ilexpl01** [comment]
The falcon's eyesight is indispensable :)

**Comment by peepshow-21** [comment]
done (if required)
