### ISSUE TITLE
Sleep Time = 0 should not be allowed to set combined with "turn off after dimming" option

### ISSUE THREAD

**Issue by ilexpl01** [peepshow-21/ns-flash#21]
Give a try why :)

**Comment by peepshow-21** [comment]
they are different things. 

dim values, keep the screen active. sleep doesn't.

if you set sleep on, pressing the screen will not action a button, it will just wake the screen, then you can press buttons. Setting dim low (even to 0) will keep the screen active. So the option is there, so set it how you like. Probably not much reason to have the screen active, when so dim, but if you don't want it to be, don't set it. I'd rather have the more flexible option there, and allow user to set as they like.
