### ISSUE TITLE
Make the Buttons in the statuspage collored (Feature request)

### ISSUE THREAD

**Issue by viper-666** [peepshow-21/ns-flash#32]
Can you please make it possible to give the value text field give a color.
I used if to display the status of my doors and windows and it would be easyer to see if all closed if they have a color, maybe green.
![Status](https://user-images.githubusercontent.com/13709294/153255316-5d32b5b6-c929-43bb-999d-3a37a2346a72.png)

**Comment by peepshow-21** [comment]
![image](https://user-images.githubusercontent.com/42150988/153284219-84dfb2d4-159b-47bf-8648-52048d470d5b.png)

Done.
