### ISSUE TITLE
You are awesome but I have some additional questions

### ISSUE THREAD

**Issue by viper-666** [peepshow-21/ns-flash#35]
![panel](https://user-images.githubusercontent.com/13709294/153401154-25011cf3-82fc-41ac-a799-e926223e2da4.jpg)
Really great how fast you have integrated my request for colored buttons. They work great!!!
But there is a additional button in the top left corner. I think that is to show a summary what is great for my application so I can show there if all windows and doors are closed.
But what is the code to control it. And I think it would be great if it isn't visible if you don't configure it maybe set "icon":1 as default what means not visible and if you send "icon":2 or "icon":3 you make it visible with the colors like the rest of the side.

And I'm nearly ready with my ioBroker integration.
But I can't find the code for the objects of the first page, the only thinks I could found was for the weather and the temp and hum.

You also showed code for the favorite button, but I can't get it to bring to do some other as usual. Maybe you have now hardcoded what it does?

**Comment by peepshow-21** [comment]
https://community.openhab.org/t/nxpanel-replacement-firmware-for-sonoff-nspanel/132869/104?u=m-home

**Comment by peepshow-21** [comment]
Rather that have one at the top of the status screen, what do you not use one of the warning icons on home screen to show everything is good? that is more what they were for. Since I would assume the home screen is on all the time. I'm not too keen on the suggestion of one at top right, tbh.

**Comment by viper-666** [comment]
Ok, the red square in the top left corner of the status page is an error indicator, I have had a typo in one command, so the red square was there. Now it is gone.

Thank you for the code examples, now I'm able to complete my first screen.

What makes the state: command in the warnings? I can't see any difference between 1, 2 or 3?
You write the warnings have a bug, is it that the red bell wasn't show and the id:1 is in the place of the bell?

**Comment by peepshow-21** [comment]
beta11 should fix those

id is 1-4 for the 4 places.
type is 1-7, for the 7 current icons
state is 1-3, for white, red and blue version

the bell was showing in error. It should only appear when you send a
{"notification") and clear when you press the bell.

**Comment by viper-666** [comment]
Thank for explaining that, but I think there is always a error with the warnings. I have installed the beta 11 tft file.
I have send:
`nxpanel {"warnings":[{"id":1,"type":1,"state":1},{"id":2,"type":3,"state":1}{"id":3,"type":3,"state":1}{"id":4,"type":4,"state":1}]}} `
And the fourth isn't shown and the icons are all in different colors  (see picture) but all are state:1 and I think the icons aren't right too.
Or have I send a clear command before sending other?

What is the difference between the screen and nxpanel command?
![Warnings](https://user-images.githubusercontent.com/13709294/153452768-fb590065-a433-4e15-aa5b-e0e93eb17540.png)

**Comment by peepshow-21** [comment]
yes. I need to test it better! :) bad fix.

**Comment by viper-666** [comment]
The warnings seems to be working now (beta 13) 👍 

And thank you very much for the trash bin icon ("icon":8) that works great.
