### ISSUE TITLE
US Panel test

### ISSUE THREAD

**Issue by viper-666** [peepshow-21/ns-flash#37]
Great work! You have implement it only on the first page, right? Next side and back to home works, the picture is after coming back.

Only one issue, you have to switch the top and bottom indicator, they are in the wrong order if I press the top button the bottom indicator lights up and vise versa.

![US_Test](https://user-images.githubusercontent.com/13709294/153483741-19695b21-d708-476e-9b65-4c36c4333e38.png)

**Comment by viper-666** [comment]
Have you change something on the status page? There appears a blue pause button and over that the red square is back, but I haven't change anything on my code what will be send to the status page...
![error](https://user-images.githubusercontent.com/13709294/153485480-3bd98511-d307-4ca9-8b61-b9624fc7da38.jpg)

**Comment by viper-666** [comment]
Ok, after a reboot the screen has the standard orientation and the error is gone.
Seems you have a lot of work to get it done...
Do you need your test indicators who are now there where the indicators for the us buttons should be?
If not copy  the bottom indicators to the side, so that the eu version has 2x2 indicators. But they can't see them on the side. And make the bottom indicators so that you can make them invisible over a command.

**Comment by peepshow-21** [comment]
try again

**Comment by viper-666** [comment]
That works like a charm, also in the other pages.
You are awesome!

**Comment by viper-666** [comment]
The issue with the Status page is always there with {"landscape":1} command.
The blue pause and red square are then visible.

**Comment by peepshow-21** [comment]
I don't see that, so I'm a but confused.

Do you see it before you end send json message to it, or when you send messages? If it's when you send messages, can you send me the json you are sending, so I can send it to mine too?

**Comment by viper-666** [comment]
Now I'm confused... I can reach the status page from two points, from the favorite on the main page and a button on the second page.
If I use the favorite from the main page all is right, from the second button page the error exists.
Here the JSON of my configuration.
`{"refresh":{"pid":10,"name":"Home","format":6,buttons:[{"bid":1,"label":"Sicherheit","type":10,"next":12,"state":15,"icon":16},{"bid":2,"label":"Wonzimmer","type":1,"state":0,"icon":1},{"bid":3,"label":"Hall","type":2,"icon":6},{"bid":4,"label":"Bedroom","type":10,"next":11,"state":5,"icon":5},{"bid":5,"label":"Temp","type":10,"next":12,"state":9,"icon":9},{"bid":6,"label":"Light","type":1,"icon":3}]}}`

`{"favorite":{"pid":12,"format":15}}`

I just tested it again without "refresh" or "sync" the info page, the error appears if I'm to fast and press the button before the page is fully ready (on the second side your refresh/sync indicator on the bottom goes off).

**Comment by viper-666** [comment]
Now it appears also if I wait for the indicator off...
And the strange thing is, if the error appears from favorite button it doesn't appear from the button on the second page. And vice versa but both are linking to page 12. And I appears then every time you use the "wrong" button.

**Comment by viper-666** [comment]
I found a other thing, if the error appears on the page title of the status page is "Home" what ist the title of the second page.
If nothing appears on the title of the status page all is good. I think there were send code to the status page from my ioBroker with what the side can't do anything. I will prove that.

**Comment by peepshow-21** [comment]
I mean, what is the json message that gets sent to the status page which gives the corrupt view?

**Comment by viper-666** [comment]
This would be send to the status page ("pid":12):
`{"refresh":{"pid":10,"name":"Home","format":6,buttons:[{"bid":1,"label":"Sicherheit","type":10,"next":12,"state":15,"icon":16},{"bid":2,"label":"Wonzimmer","type":1,"state":0,"icon":1},{"bid":3,"label":"Hall","type":2,"icon":6},{"bid":4,"label":"Bedroom","type":10,"next":11,"state":5,"icon":5},{"bid":5,"label":"Temp","type":10,"next":12,"state":9,"icon":9},{"bid":6,"label":"Light","type":1,"icon":3}]}}`

**Comment by peepshow-21** [comment]
that's not a status page message, that a button page message. Are you alsoway sending a refresh each time, so the button page is  slow drawn, I would only send a sync 2nd time. which is much faster. there may be an issue on fresh use to speed, if you move page while it's still processing the message, as things will be left in the buffer. I've not seen in my testing as I use sync. I try to see if can replicate. but it sounds like the status page is getting the rest of the button page message. so it getting an icon message (which is the background for the status like) without a id for the status line, so that will be zero, so it's setting the icon on zero, which is probably breakign it I might need to clear the buffer on a new page, if people will do these things! :)

**Comment by viper-666** [comment]
No it wouldn't be a buffer issue. I parse all what come on the result channel.
In this I search for "pid", "format" and "type", if there where I put them into variables.
The other scripts look if there is a change in some of this variables and if the type is "sync" or "refresh" the script runs and set the type variable to "synced" or "refreshed" so that there is no endless loop.
So it could be happened in fact of timing issues that the pid is allways 10 but the type has changed to "refresh" because I called the status page (pid=12) and the script send the refresh code for pid 10 to pid 12 what caused the issue.
If you want to avoid this you have to look if the send code is for the actual page.
But I think this is at first time my problem, I have to look how I can avoid this behavor.

**Comment by peepshow-21** [comment]
I think it's a buffer issue. I'm about to release working RGB/CT dimmer, so
I'll put that I think is the fix in for the status page, then you can do
the same test, as see if it still fails.

**Comment by viper-666** [comment]
Ok, I will test it.
Thank you!

**Comment by peepshow-21** [comment]
Having a think, I need to prevent people pressing buttons until the refresh
is complete. sync it not too bad, but refresh is a problems.

Example. if you had 2 rooms on the 8 button panel. after you went to Room A
button 8 might be set to Hall light. The the user goes to room B and
pressed button 8 while it's refreshing.This would do the hall light bc it
might not have got to the refresh yet, which would make button 8, soemthign
else. So I think I need to make buttons dead, until the refresh is
complete.

 I will test some more. but, if you are not doing a 'sync' on your button
pages when asked, but just sending refresh all the time, this will not be
helping. I'd suggest doing that.

**Comment by peepshow-21** [comment]
Try a test now on beta13

**Comment by viper-666** [comment]
I have tried the beta 13, but the issue is always there. 
It has also nothing to do with the total sync it appears also when I wait till the side is fully synced.

**Comment by peepshow-21** [comment]
what if your first button page? 8 button? I only but the fix in there to test, and it def worked for me. before I put the change in, I could get the error by pressing the link to status page while it was loading. After the change, pressing the button didnt' work, until the page was refrehsed, then it changed with no issues.

**Comment by viper-666** [comment]
I have since yet only one button page with 8 buttons.
Where it possible to extend the log of the tasmota console?
Or where there all commands shown they where send over mqtt  nxpanel command?
Now you get something like this:
`14:02:01.180 MQT: nspanel/RESULT = {"NxPanel":"Done"}
14:02:01.334 MQT: nspanel/RESULT = {"error":{"message":"can't decoding message"}}
14:02:02.380 MQT: nspanel/RESULT = {"NxPanel":"Done"}`
And you don't know what message counts the error.
So it is difficult to exclude that the error comes while my ioBroker send a command while the info page is syncing.

**Comment by peepshow-21** [comment]
I have tried after i put the fix in and the status page does not go wrong. i could get it to go wrong how you said, bu pressing the button when it was still refresshing. when you can't (as it is now) it doesn't do it. please try again on the latest version. the version installed by the new improved method with the new nxpanel.be with auto flash. I'm sure it's fixes. I tested with refresh alwasy, which is not the correct way, but good to test this. when you are sure its working with refresh always, please you sync correctly. it's much faster.

I'll close this.
