### ISSUE TITLE
Problems with new nxpanel.be 

### ISSUE THREAD

**Issue by viper-666** [peepshow-21/ns-flash#49]
For your Autoupdate and fully FTP upload feature I installed the newest nxpanel.be.
But after a reboot I get several error messages on the console and no nxpanel, installnxpanel command works.
Here the console log:
`00:00:00.003 HDW: ESP32-D0WD-V3 
00:00:00.131 UFS: FlashFS mounted with 288 kB free
00:00:00.260 CFG: Loaded from File, Count 241
00:00:00.276 QPC: Count 1
00:00:00.384 BRY: Berry initialized, RAM used=3849
00:00:00.413 BRY: no 'preinit.be'
00:00:00.421 Project tasmota - NSPanel Version 10.1.0(tasmota)-2_0_1_1(2021-12-08T14:50:20)
00:00:01.485 BRY: Exception> 'syntax_error' - /nxpanel.be:285: 'tcpclient' undeclared (first use in this function)
00:00:01.487 stack traceback:
00:00:01.498 	<native>: in native function
00:00:01.498 	<unknown source>: in function `load`
00:00:01.499 	<unknown source>: in function `load`
00:00:01.510 	<unknown source>: in function `main`
00:00:01.511 	<unknown source>: in function `load`
00:00:01.512 	<unknown source>: in function `load``

**Comment by peepshow-21** [comment]
Sure you are on correct versions?
![image](https://user-images.githubusercontent.com/42150988/153869383-421ee5c3-7563-412a-a0b6-d3390ed95d16.png)
I just downloaded the one from git myself to check and copied to my panel and it boots fine.

did installnxpanel command work? Can the box see the external download URL? If not download yourself and flash as before (locally) with flashnextion command.

It's not not FTP. it's HTTP.

**Comment by viper-666** [comment]
Yes it is `static VERSION = "1.1.1"`.
And no installnxpanel don't work  ` nspanel/RESULT = {"Command":"Unknown"}`

**Comment by viper-666** [comment]
Ok, found the issue, I have to update tasmota, now it works and also installed automatically the new tft file from your github after the installnxpanel command.

**Comment by peepshow-21** [comment]
I fixed the infrequent random error when sending messages. I get no errors at all anymore and all.
![image](https://user-images.githubusercontent.com/42150988/154122149-9b24097d-71a3-4a55-bb38-1798bd41c78d.png)
the error, was a very hard to get buffer overrun. now you just get a little warming and the message get's picked up.

**Comment by viper-666** [comment]
You mean this errors?
`18:56:00.961 MQT: nspanel/RESULT = {"error":{"e:":1,"s":79,"h":"PS"}}
18:56:01.202 MQT: nspanel/RESULT = {"error":{"e:":2,"s":79,"h":"2,"}}`

**Comment by peepshow-21** [comment]
yes, all fixed now

**Comment by peepshow-21** [comment]
I've just released 1.0.1, so be interesting to see if auto update works. it you have it turned on and want force and update check, before the 24hr check kicks in, type 9998 red button, on the alarm page

**Comment by viper-666** [comment]
That with 9998 red button don't work.
Also seems there a bug on the alarm page, the first number I pressed will turn red but no beep .

**Comment by peepshow-21** [comment]
can you send a weblog 4 after your press 9998 red. maybe 15 secs worth after

**Comment by viper-666** [comment]
Ok it seems to work but it means 1.0.0.0 was the newest firmware.
20:46:33.755 NXP: Update check for 'release'
20:46:34.056 HTP: Connected in 296 ms, stack low mark 3780
20:46:34.066 NXP: Current version 1.0.0 is latest

**Comment by peepshow-21** [comment]
have have not checked test auto updates, so its only checking 'release'
auto updates not 'testing'

it's all testing now, so tick that and it will work. 

it will then look more like this
20:46:33.755 NXP: Update check for 'testing'
20:46:34.056 HTP: Connected in 296 ms, stack low mark 3780
20:46:34.066 NXP: Current version 1.0.0 newer 1.0.1 availalle

kind of thig

**Comment by viper-666** [comment]
With the test button checked it wotks 👍

**Comment by viper-666** [comment]
Yesterday it updates automatically. 
Have you a tipp to what MQTT command I should look to know when the panel reboots and boots from scratch?
I look for changes on the Info3 channel, but in this channel will be only postet if you boot from scratch not if you reboot like the panel doe's after update.  So the necessary commands will not be send from my home automation system.

**Comment by peepshow-21** [comment]
If look in the logs, I think a few different ones are sent, some via
tasmota, but nxpanel sends an init one also, best way is reboot yourself,
and see what looks useful to you.

**Comment by viper-666** [comment]
The "problem" is, that I can't see if the panel has rebooted after a tft update so I missed maybe some informations.

**Comment by peepshow-21** [comment]
someone else using pxpanel with ibroker here you might be able to help?
https://community.openhab.org/t/nxpanel-replacement-firmware-for-sonoff-nspanel/132869/219

as for the other issue, you dont see the {"init".. message sent over mqtt
when it restarts?
