### ISSUE TITLE
Problem with uploading nxpanel.be

### ISSUE THREAD

**Issue by ilexpl01** [peepshow-21/ns-flash#56]
Hi.

NSPanel

Program Version  11.0.0.4(tasmota)
Build Date & Time  2022-03-23T10:17:10

I upload  nxpanel.be with Manage File system tool.

After upload the file has always the size = 0

Why ?

**Comment by viper-666** [comment]
I have once the same issue, but it was my fault. If you in Github right klick on nxpanel.be and choose download in the pop up menu you will download a xml file with the right file name.
Look in your file explorer or open the file with a editor to be shure to have the right file.
A easy solution could be in the tasmota file manager klick on edit nxpanel.be, in github left klick on the nxpanel.be and it opens the Editor where you can copy the text and placed it in tasmota.

**Comment by ilexpl01** [comment]
I have installed github desktop abd got an easy access to nxpanel.be file. Copy to NSpanel was very easy bu now I get the warnings:

21:10:14.716 MQT: tele/tasmota01/RESULT = {"warning":"buffer-wait"}
21:10:14.939 MQT: tele/tasmota01/RESULT = {"warning":"buffer-wait"}
21:10:15.159 MQT: tele/tasmota01/RESULT = {"warning":"buffer-wait"}
21:10:15.328 MQT: tele/tasmota01/RESULT = {"warning":"buffer-wait"}
21:10:15.546 MQT: tele/tasmota01/RESULT = {"warning":"buffer-wait"}
21:10:15.713 MQT: tele/tasmota01/RESULT = {"warning":"buffer-wait"}
21:10:15.931 MQT: tele/tasmota01/RESULT = {"warning":"buffer-wait"}
21:10:16.151 MQT: tele/tasmota01/RESULT = {"warning":"buffer-wait"}
21:10:16.436 MQT: tele/tasmota01/RESULT = {"warning":"buffer-wait"}
21:10:16.618 MQT: tele/tasmota01/RESULT = {"warning":"buffer-wait"}

No time on panel screen or temperature. Any hint ?
