### ISSUE TITLE
What is the status of this project?

### ISSUE THREAD

**Issue by respectTheCode** [peepshow-21/ns-flash#58]
This project seems to be the only way to flash a TFT file with Tasmota. The latest release works but its pretty inconvenient to have to run the TFT file through a java app to make chunks. On master the code has been updated to load the TFT file directly but it didn't work for me.

**Comment by peepshow-21** [comment]
I changed this to download the tft directly months ago, please ensure you
are on latest version

**Comment by respectTheCode** [comment]
Is master considered stable? The latest release on github is v1.0.0-beta2 and doesn't have the direct TFT downloads.

I will give master another try. I am still very new to tasmota so I may have had other issues before.

**Comment by respectTheCode** [comment]
Ok master didn't work for me because the Host request header was required by my HTTP server. Finding this required adding a bunch of logging to find that the server was returning a 404. This has already been fixed in #55.

Since many users are likely going to use the HTTP server in Home Assistant this is likely a common problem. It would also be helpful to note in the readme that HTTPS does not work.

**Comment by respectTheCode** [comment]
Ok master didn't work for me because the Host request header was required by my HTTP server. Finding this required adding a bunch of logging to find that the server was returning a 404. This has already been fixed in #55.

Since many users are likely going to use the HTTP server in Home Assistant this is likely a common problem. It would also be helpful to note in the readme that HTTPS does not work.

**Comment by peepshow-21** [comment]
The project is back on, as I have some time to work on it at catch up.

Yes, https is not supported. Berry scripting is very lightweight and does not have the ability to all the bloat required for supporting SSL and so on.
