### ISSUE TITLE
Nextion Editor HMI project file

### ISSUE THREAD

**Issue by ilexpl01** [peepshow-21/ns-flash#8]
Hi,

Can You please make available to download the HMI project file which is a source of nxpanel.tft file ?

BR.

**Comment by peepshow-21** [comment]
The source is not available for this currently. There are numerous HMI's that are locked down to specific screens where source is available and you can change those to meet your requirements, but they are fixed, not dynamic at runtime. My HMI is not intended to be used as base and changed, it's designed to be adapted at runtime via mqtt and be generic. At some point I may release the source, but for now I'm focusing on getting it working how I want. If you have a specific use case or requirement please let me know and I'll see if it can be accommodated in the HMI. Hope that makes sense! :)

**Comment by ilexpl01** [comment]
Thx 4 a fast answer. It is your choice of course. I would like to adjust NSPanel GUI exactly to my enviroment requirements and have only objects linked to my home automation sensors/devices. Well, it is a time now to learn how to build HMI projects frome the scratch :)

**Comment by peepshow-21** [comment]
maybe, but your might find the nxpanel did just that and saved you a lot of work! :) Hope it goes well if you do it from scratch, it can take a lot of time. I've spent loads doing nxpanel.

**Comment by peepshow-21** [comment]
You might want to try the latest test version which is almost ready for release;
https://community.openhab.org/t/sonoff-nspanel-setup/131770/75?u=m-home
should be released at the weekend.
you might find this can be made to do most of what you might need.

**Comment by ilexpl01** [comment]
I am not using HA but Domoticz. Will check the release of course. What is the most important for me is to setup objects in panel GUI and link them over MQTT with Domoticz. Node red is essential in this setup :)

**Comment by peepshow-21** [comment]
will close this, feel free to give feedback on how it works for you
